sudo: required
services:
- docker

env:
  global:
  - BINTRAY_USER=vicamo
  - BINTRAY_REPO=ppa
  - BINTRAY_COMPONENT=contrib
  - BINTRAY_DESC="DKMS files to build and install ANDROID binder"
  - DOCKER_EXEC="sudo docker exec test_container"
  matrix:
  - SUITE=sid ARCH=amd64

matrix:
  fast_finish: true

branches:
  only:
  - master
  - /^\d+\.\d+/

before_install:
- sudo docker pull vicamo/debian-linux-kernel:${SUITE}-${ARCH}
- sudo docker images
- |
  sudo docker run --detach --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR} \
    vicamo/debian-linux-kernel:${SUITE}-${ARCH} \
    /bin/bash

install:
- ${DOCKER_EXEC} apt-get update --quiet --quiet
- ${DOCKER_EXEC} apt-get install --no-install-recommends --yes
    devscripts equivs
- ${DOCKER_EXEC} mk-build-deps
    --install --remove
    --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes --allow-unauthenticated'

script:
- ${DOCKER_EXEC} env WORKAROUND_BINTRAY_DEB_SUPPORT=1
    dpkg-buildpackage -i -us -uc -b

before_deploy:
- |
  cat .bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(cat debian/control | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s#@BINTRAY_VERSION@#$(cat debian/changelog | head -n 1 | sed 's,.*(\(.*\)).*,\1,')#g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(date -Iseconds --date="$(cat debian/changelog | grep -m 1 '^ -- ' | sed 's,^.*  ,,')")#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(cat debian/control | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#${SUITE}#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#all#g" | \
    tee .bintray.json

deploy:
- provider: bintray
  file: .bintray.json
  user: vicamo
  key:
    secure: "mnuZVOhHxOVgjasKwBHw3ukKhLM6ACtDTjHtc/ETzU29BDEBsijo1a1Qbked152uq4dkj3HLGG4v/M+HqxaM2zAql1+4afNwx0HKnVro/NhzkVtJ6gdMBFM/bW/AtboDOCyPrOivo4ImamlV278uBZgmtWjQYFTFrxY3Pn8V87lDbIe6xDGwT8ifn4zVWa7SiV5VgxwqrUWfncpHVqT0pEq4GMOupVW4acFODhDWp7hIuJgdfZucCoFDwNV69ZaVAdqfQ5PG6cBuOX4eB5i1SfceMip7xAgvSXZpvEfLH5jP5tQhKAN6TRnCqpz/a9jWgDF/rfhHFtOCF/M0dqE2eobyqrcgVYpJ2rxKRgCcyBGZo+EZUjA0DKWP8eUmjd2mYbpGJF/E3vGykcq1cauQOZ4mnNIgGhEKhQ9fpbQ7BUp8/UF65sEQbeOVXahWuFRZ/12LLmxmvldZ3VEXBcsz0WmPAG+9s/POGUbu4/U0r8D9vJdNmtU/NOTyf0QkX7jl6TtbN6Q/W3FngmVLl05l/u97bczZtAeNzU+kT7CYvoWBciGkHNP/TPtYqf1Ax9WyyeRstTfHyXOqjiuJDxV2BFPsEoc/U2TCFB+C+qRsABzxdAq+pioH+NLyF4FmTm6jvESMrS3J6X69k3SQAlalsJC72TZHUUdOZZMmiMsOZXQ="
  on:
    tags: true
